package utility;

import java.time.LocalDate;

/**
 * A simple class for making queries, generated by the GUI and consumed by the back-end
 * @author "sbrockl"
 *
 */
public class QueryRequest {

	// empty field means not applicable
	private String timeSeries = "";
	private String symbol = "";
	private String timeIntervall = "";
	private String outputSize = "";
	private LocalDate startDate;
	private LocalDate endDate;
	
	public LocalDate getStartTime() {
		return startDate;
	}
	public void setStartTime(LocalDate startDate) {
		this.startDate = startDate;
	}
	public LocalDate getEndTime() {
		return endDate;
	}
	public void setEndTime(LocalDate endDate) {
		this.endDate = endDate;
	}
	public String getTimeSeries() {
		return timeSeries;
	}
	public void setTimeSeries(String timeSeries) {
		this.timeSeries = timeSeries;
	}
	public String getSymbol() {
		return symbol;
	}
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
	public String getTimeIntervall() {
		return timeIntervall;
	}
	public void setTimeIntervall(String timeIntervall) {
		this.timeIntervall = timeIntervall;
	}
	public String getOutputSize() {
		return outputSize;
	}
	public void setOutputSize(String outputSize) {
		this.outputSize = outputSize;
	}
	
	// for ease of debugging
	@Override
	public String toString()
	{
		String output = "";
		
		output += "Query request contents:\n";
		output += "        symbol: " + symbol + "\n";
		output += "   time series: " + timeSeries + "\n";
		output += "time intervall: " + timeIntervall + "\n";
		output += "   output size: " + outputSize + "\n";
		output += "    start date: " + startDate.toString() + "\n";
		output += "      end date: " + endDate.toString() + "\n";
		
		return output;
	}
}
