package utility;


/**
 * A simple class for making queries, generated by the GUI and consumed by the back-end
 * @author "sbrockl"
 *
 */
public class QueryRequest {

	// empty field means not applicable
	private String timeSeries = "";
	private String symbol = "";
	private String timeIntervall = "";
	private String outputSize = "";
	
	
	public String getTimeSeries() {
		return timeSeries;
	}
	public void setTimeSeries(String timeSeries) {
		this.timeSeries = timeSeries;
	}
	public String getSymbol() {
		return symbol;
	}
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
	public String getTimeIntervall() {
		return timeIntervall;
	}
	public void setTimeIntervall(String timeIntervall) {
		this.timeIntervall = timeIntervall;
	}
	public String getOutputSize() {
		return outputSize;
	}
	public void setOutputSize(String outputSize) {
		this.outputSize = outputSize;
	}
	
}
